
Maci\UserBundle\Entity\User:
    type:  entity
    table: maci_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        created:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedValue ]
