
maci_user_login:
    path:  /{_locale}/login
    defaults: { _controller: MaciUserBundle:Default:login }
    requirements:
        _locale: "%r_locales%"

maci_user_register:
    path:  /{_locale}/register
    defaults: { _controller: MaciUserBundle:Default:register }
    requirements:
        _locale: "%r_locales%"

maci_user:
    path:  /user
    defaults: { _controller: MaciUserBundle:Default:index }

maci_user_delete_account:
    path:  /profile/delete_account
    defaults: { _controller: MaciUserBundle:Default:deleteAccount }

maci_user_delete_account_confirm:
    path:  /profile/delete_account/confirm
    defaults: { _controller: MaciUserBundle:Default:confirmDeleteAccount }

# ---> Address

maci_address_remove:
    path:  /address/remove/{id}
    defaults: { _controller: MaciUserBundle:Address:remove }

maci_address_form:
    path:  /address/form/{id}
    defaults: { _controller: MaciUserBundle:Address:addressForm, id: null }

maci_address:
    path:  /address/
    defaults: { _controller: MaciUserBundle:Address:index }
