
maci_user_login:
    path:  /{_locale}/login
    defaults: { _controller: MaciUserBundle:Default:login }
    requirements:
        _locale: %r_locales%

maci_user_register:
    path:  /{_locale}/register
    defaults: { _controller: MaciUserBundle:Default:register }
    requirements:
        _locale: %r_locales%

maci_user_change_password:
    path:  /user/profile/change_password
    defaults: { _controller: FOSUserBundle:ChangePassword:changePassword }

maci_user_profile_edit:
    path:  /user/profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

maci_user_profile:
    path:  /user/profile
    defaults: { _controller: FOSUserBundle:Profile:show }

maci_user:
    path:  /user
    defaults: { _controller: MaciUserBundle:Default:index }
