
maci_user_profile_edit:
    pattern:  /user/profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

maci_user_profile:
    pattern:  /user/profile
    defaults: { _controller: FOSUserBundle:Profile:show }

maci_user:
    pattern:  /user
    defaults: { _controller: MaciUserBundle:Default:index }
