
services:

    maci_user.menu_builder:
        class: Maci\UserBundle\Menu\UserMenuBuilder
        arguments: ["@knp_menu.factory","@security.authorization_checker",'@security.token_storage',"@request_stack","@maci.translator"]
        tags:
            - { name: knp_menu.menu_builder, method: createLanguageMenu, alias: language }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }
            - { name: knp_menu.menu_builder, method: createCartMenu, alias: user_cart }
            - { name: knp_menu.menu_builder, method: createLeftMenu, alias: user_left }
            - { name: knp_menu.menu_builder, method: createLeftWithRegMenu, alias: user_left_with_reg }
            - { name: knp_menu.menu_builder, method: createShortMenu, alias: user_short }
